services:
  hikkaba.web:
    image: ${DOCKER_REGISTRY-}hikkabaweb
    build:
      context: .
      dockerfile: ./Hikkaba.Web/Dockerfile
    container_name: hikkaba.web.dev.local
    domainname: hikkaba.web.dev.local
    hostname: hikkaba.web.dev.local
    ports:
      - "35080:8080"
    volumes:
      - "hikkaba_storage:/var/hikkaba/storage"
    env_file:
      - ./Hikkaba.Web/Development.env
    depends_on:
      - db
      - mailhog

  db:
    image: ${DOCKER_REGISTRY-}hikkabadb
    build:
      context: .
      dockerfile: ./Components/Database/Dockerfile
    container_name: hikkaba.db.dev.local
    domainname: hikkaba.db.dev.local
    hostname: hikkaba.db.dev.local
    user: root
    environment:
      MSSQL_SA_PASSWORD: "dev_passworD@4568919"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_IP_ADDRESS: "0.0.0.0"
    ports:
      - "31433:1433"
    volumes:
      - "hikkaba_mssql:/var/opt/mssql"
      - "C:/docker-linux/hikkaba/db_backups:/var/db_backups"

  otel_collector:
    container_name: hikkaba.otel_collector.dev.local
    domainname: hikkaba.otel_collector.dev.local
    hostname: hikkaba.otel_collector.dev.local
    image: "otel/opentelemetry-collector-contrib:latest"
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    volumes:
      - ./collector-config.yaml:/etc/otelcol-contrib/config.yaml

  prometheus:
    container_name: hikkaba.prometheus.dev.local
    domainname: hikkaba.prometheus.dev.local
    hostname: hikkaba.prometheus.dev.local
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle' # config reload
      - '--web.enable-remote-write-receiver' # enable remote write receiver (OTLP)

  # dashboard
  # 19105 - Prometheus
  # 19924 - ASP.NET Core
  # 19925 - ASP.NET Core Endpoint
  # 23179 - Dotnet Runtime Metrics
  # 23178 - Kestrel Metrics
  grafana:
    container_name: hikkaba.grafana.dev.local
    domainname: hikkaba.grafana.dev.local
    hostname: hikkaba.grafana.dev.local
    image: "grafana/grafana"
    ports:
      - "3000:3000"

  mailhog:
    container_name: hikkaba.mailhog.dev.local
    domainname: hikkaba.mailhog.dev.local
    hostname: hikkaba.mailhog.dev.local
    image: "mailhog/mailhog"

volumes:
  hikkaba_mssql:
  hikkaba_storage:
