version: '3.4'

services:
  hikkaba.web:
    image: ${DOCKER_REGISTRY-}hikkabaweb
    build:
      context: .
      dockerfile: Hikkaba.Web/Dockerfile
    container_name: hikkaba.web.dev.local
    domainname: hikkaba.web.dev.local
    hostname: hikkaba.web.dev.local
    ports:
      - "35443:443"
    depends_on:
      - db
      - mailhog

  db:
    container_name: hikkaba.db.dev.local
    domainname: hikkaba.db.dev.local
    hostname: hikkaba.db.dev.local
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    environment:
      MSSQL_SA_PASSWORD: "dev_passworD@4568919"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_IP_ADDRESS: "0.0.0.0"
    ports:
      - "31433:1433"
    volumes:
      - "hikkaba_mssql:/var/opt/mssql"
      - "C:/docker-linux/hikkaba/db_backups:/var/db_backups"

  mailhog:
    container_name: hikkaba.mailhog.dev.local
    domainname: hikkaba.mailhog.dev.local
    hostname: hikkaba.mailhog.dev.local
    image: "mailhog/mailhog"

volumes:
  hikkaba_mssql:
